package UI;

import leg.Leg;
import leg.Legs;
import utils.LocalFlightDatabase;

import javax.swing.*;
import javax.swing.table.DefaultTableModel;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.beans.PropertyChangeEvent;
import java.beans.PropertyChangeListener;
import java.text.NumberFormat;
import java.time.LocalTime;
import java.time.format.DateTimeFormatter;
import java.util.ArrayList;
import java.util.List;
import java.util.Locale;

import static java.lang.Math.floor;

public class ReservationApp {
    // Automatically generated variables for handling Swing components in the GUI Builder
    private JComboBox<String> seatingTypeComboBox;
    private JButton addFlightToCartButton;
    private JButton viewFullFlightDetailsButton;
    private JButton quitButton;
    private JButton resetButton;
    private JButton searchForFlightsButton;
    private JPanel mainPanel;
    private JFormattedTextField departureDateFormattedTextField;
    private JFormattedTextField arrivalDateFormattedTextField;
    private JFormattedTextField departureAirportFormattedTextField;
    private JFormattedTextField arrivalAirportFormattedTextField;
    private JFormattedTextField maximumLayoversFormattedTextField;
    private JFormattedTextField numberOfPassengersFormattedTextField;
    private JTable flightDisplayTable;
    private JFrame frameHandle;

    // List of UI components which should be inactive during long operations to prevent user input
    // and signal to the user that the program is busy
    private List<JComponent> busyList = new ArrayList<>();

    // Container that stores the current state of user input and validates new input
    private static UIModel model;

    private static DefaultTableModel flightDisplayData = new DefaultTableModel();
    /**
     * Main method is required by JavaFX, which is used by the GUI Designer,
     * but is not needed for any other reason
     *
     * @param args String []
     */
    public static void main(String[] args) {

    }

    /**
     * Creates the GUI window, adds components, and populates default values.
     * Also, stores a reference to a UIData object for storage and validation of input
     *
     * @param newModel is an instantiation of UIData
     */
    public void initializeUIElements(UIModel newModel) {
        // If no model is provided, initialize a new one
        if (newModel == null)
            model = new UIModel();
        else
            model = newModel;

        // Create the JFrame and JComponents
        initializeWindow();

        // Create the list of JComponents that should be disabled while the app is busy
        buildBusyList();

        // Set the default seating types
        seatingTypeComboBox.setModel(new DefaultComboBoxModel<String>(model.getSeatingPossibilities()));

        // Set the columns of the table
        flightDisplayData.addColumn("Coach Price");
        flightDisplayData.addColumn("First Class Price");
        flightDisplayData.addColumn("Flight Time");
        flightDisplayData.addColumn("Departure Airport");
        flightDisplayData.addColumn("Departure Date");
        flightDisplayData.addColumn("Departure Time");
        flightDisplayData.addColumn("Arrival Airport");
        flightDisplayData.addColumn("Arrival Date");
        flightDisplayData.addColumn("Arrival Time");
        flightDisplayData.addColumn("Flight Number");
        flightDisplayData.addColumn("Plane Model");
        flightDisplayData.addColumn("Coach Seats Reserved");
        flightDisplayData.addColumn("First Class Seats Reserved");
        flightDisplayTable.setModel(flightDisplayData);

        System.out.println("Finished Initialization");
    }

    /**
     * Constructor method automatically generated by GUI Designer when adding listeners.
     * The contents of the overriden methods have been modified to respond appropriately to user interaction
     */
    public ReservationApp() {
        // As far as I can tell $$$setupUI$$$ is called right at the beginning of this constructor

        //When the search button is pressed, set the busy status to true
        //The status should remain true until the search is completed or the operation is canceled
        searchForFlightsButton.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                // Execute search functionality here
                System.out.println("Search Button User Interaction");
                busy(true);
                UIData userInput = model.getAcceptedInput();
                if (userInput.departureAirport() != null && userInput.departureDate() != null) {

                    model.setDisplayList(LocalFlightDatabase.getInstance().getLegList(userInput.departureAirport(), userInput.departureDate().toLocalDate(), false));
                    buildFlightTable();
                } else
                    System.out.println("Departure airport or departure date is empty, cannot search for flights");
                busy(false);
            }
        });

        // When any text field is changed, attempt to overwrite the value in the model.
        //Then, get the validated value stored in the model to update the display of the component.
        departureAirportFormattedTextField.addPropertyChangeListener(new PropertyChangeListener() {
            @Override
            public void propertyChange(PropertyChangeEvent evt) {
                model.setDepartureAirport(departureAirportFormattedTextField.getText());
                departureAirportFormattedTextField.setText(model.getDepartureAirport());
            }
        });
        arrivalAirportFormattedTextField.addPropertyChangeListener(new PropertyChangeListener() {
            @Override
            public void propertyChange(PropertyChangeEvent evt) {
                model.setArrivalAirport(arrivalAirportFormattedTextField.getText());
                arrivalAirportFormattedTextField.setText(model.getArrivalAirport());
            }
        });
        departureDateFormattedTextField.addPropertyChangeListener(new PropertyChangeListener() {
            @Override
            public void propertyChange(PropertyChangeEvent evt) {
                model.setDepartureDate(departureDateFormattedTextField.getText());
                departureDateFormattedTextField.setText(model.getDepartureDate());
            }
        });
        arrivalDateFormattedTextField.addPropertyChangeListener(new PropertyChangeListener() {
            @Override
            public void propertyChange(PropertyChangeEvent evt) {
                model.setArrivalDate(arrivalDateFormattedTextField.getText());
                arrivalDateFormattedTextField.setText(model.getArrivalDate());
            }
        });
        numberOfPassengersFormattedTextField.addPropertyChangeListener(new PropertyChangeListener() {
            @Override
            public void propertyChange(PropertyChangeEvent evt) {
                model.setNumberOfPassengers(numberOfPassengersFormattedTextField.getText());
                numberOfPassengersFormattedTextField.setText(model.getNumberOfPassengers());
            }
        });
        maximumLayoversFormattedTextField.addPropertyChangeListener(new PropertyChangeListener() {
            @Override
            public void propertyChange(PropertyChangeEvent evt) {
                model.setNumberOfLayovers(maximumLayoversFormattedTextField.getText());
                maximumLayoversFormattedTextField.setText(model.getNumberOfLayovers());
            }
        });

        // When the reset button is pressed, reinitialize the GUI
        // This will force any disabled JComponents to re-enable and reset model values to the default
        resetButton.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                System.out.println("Reset User Interaction");
                initializeUIElements(new UIModel());
            }
        });

        // When the quit button is pressed, exit the program
        quitButton.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                System.exit(0);
            }
        });

        seatingTypeComboBox.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                //model.setSeatingType(seatingTypeComboBox.getSelectedItem().toString());
            }
        });
    }

    /**
     * Creates the GUI JFrame and builds all of the JComponents.
     * All of the hidden source code is implemented during the 'setContentPane' function
     */
    private void initializeWindow() {
        if (frameHandle != null)
            frameHandle.dispose();
        frameHandle = new JFrame("ReservationApp");
        frameHandle.setContentPane(mainPanel);
        frameHandle.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        frameHandle.pack();
        frameHandle.setVisible(true);
    }


    /**
     * Creates a list of essential user interactions that should be disabled during long operations.
     * Visually shows the user that the program is busy, and prevents confusing input
     */
    private void buildBusyList() {
        busyList.add(seatingTypeComboBox);
        busyList.add(addFlightToCartButton);
        busyList.add(viewFullFlightDetailsButton);
        busyList.add(searchForFlightsButton);
        busyList.add(departureAirportFormattedTextField);
        busyList.add(arrivalAirportFormattedTextField);
        busyList.add(departureDateFormattedTextField);
        busyList.add(arrivalDateFormattedTextField);
        busyList.add(maximumLayoversFormattedTextField);
        busyList.add(numberOfPassengersFormattedTextField);
        busy(false);
    }

    /**
     * Iterates over the list of important JComponents to disable/enable them
     *
     * @param tf a boolean where true represents busy state (disabled) and false represents free (enabled)
     */
    private void busy(boolean tf) {
        for (JComponent element : busyList) {
            element.setEnabled(!tf);
        }
    }

    private void buildFlightTable(){
        Legs displayList = model.getDisplayList();
        if(displayList != null) {
            DefaultTableModel table = (DefaultTableModel) flightDisplayTable.getModel();
            table.setRowCount(0);
            DateTimeFormatter dateStyle = DateTimeFormatter.ofPattern("MM/dd/yyyy");
            DateTimeFormatter timeStyle = DateTimeFormatter.ofPattern("HH:mm a");
            DateTimeFormatter flightTimeStyle = DateTimeFormatter.ofPattern("HH:mm");
            NumberFormat priceStyle = NumberFormat.getCurrencyInstance(Locale.US);
            for (Leg leg : displayList) {
                String coachPrice = priceStyle.format(leg.coachPrice);
                String firstClassPrice = priceStyle.format(leg.firstClassPrice);
                String departureAirport = leg.boardingAirport.code();
                String departureDate = dateStyle.format(leg.boardingTime);
                String departureTime = timeStyle.format(leg.boardingTime);
                String arrivalAirport = leg.disembarkingAirport.code();
                String arrivalDate = dateStyle.format(leg.disembarkingTime);
                String arrivalTime = timeStyle.format(leg.disembarkingTime);
                String flightNumber = Integer.toString(leg.flightNumber);
                String plane = leg.plane;
                String coachSeatsReserved = Integer.toString(leg.reservedCoachSeats);
                String firstClassSeatsReserved = Integer.toString(leg.reservedFirstClassSeats);
                String flightTime = flightTimeStyle.format(LocalTime.of((int) floor((double)leg.legDuration /60.0), leg.legDuration % 60));
                table.addRow(new Object[] {coachPrice, firstClassPrice, flightTime, departureAirport,departureDate,departureTime,arrivalAirport,arrivalDate,arrivalTime,flightNumber,plane, coachSeatsReserved, firstClassSeatsReserved});
            }
        }else
            System.out.println("No flights were found matching the provided criteria");
        System.out.println("Flights matching the provided criteria have been displayed");
    }

}
